### PR TITLE
fix: federated client credentials not working if sub ≠ client_id

### LINKED ISSUE #902: 🐛 Bug Report: Federated client credentials RFC 7523 inconsistency
### Reproduction steps

Try to create an app with federated client credentials for use with Kubernetes as described in the docs.

Try to figure out what the federated client credentials Subject option does.

### Expected behavior

There's no reason to restrict the characters in a client ID, is there?

If we allow `sub != clientID`, we are violating the spec. So we probably can't.

### Actual Behavior

First of all, the docs mention using Kubernetes API server and even describe the format like of those JWT tokens as `system:serviceaccount:envoy-gateway-system:envoy-infra-services-571ea4e6`
but then I get the error `Client ID can only contain letters, numbers, underscores, and hyphens` when trying to create a client with this non-generated clientID.

There also seems to be some inconsistency with clientID vs sub. The RFC says the JWT sub must equal the clientID, but then we allegedly have the Federated Client Credentials optional Subject? ...why is it there? It seems like we both [enforce that the clientID](https://github.com/pocket-id/pocket-id/blob/802754c24c019abb099c0f1b7be45bac315ae1dd/backend/internal/service/oidc_service.go#L1688) is [in the JWT as per the RFC](https://github.com/pocket-id/pocket-id/blob/main/backend/internal/service/oidc_service.go#L1535-L1550) but also [we verify using the optional subject in some cases](https://github.com/pocket-id/pocket-id/blob/802754c24c019abb099c0f1b7be45bac315ae1dd/backend/internal/service/oidc_service.go#L1657).

### Pocket ID Version

v1.10.0

### Database

sqlite

### OS and Environment

Not relevant.

### Log Output

_No response_

### LINKED ISSUE #1333: 🐛 Bug Report: Federated Credentials: Invalid client assertion when subject is not client ID
### Reproduction steps

1. Configure an OIDC client
2. Configure [Federated Client Credentials](https://pocket-id.org/docs/guides/oidc-client-authentication)
3. Put any string (other than the Client ID) as the Subject
4. Have your issuer issue a token, with `sub` equal to the configured subject in pocket-id.
5. Try do an OAuth token exchange with `grant_type=authorization_code` as per the docs.
6. Observe the error message:
```
{"error":"Invalid client assertion"}
```

### Expected behavior

Pocket ID should consider the token valid if the subject is the string configured as the subject under Federated Client Credentials config.  

### Actual Behavior

Before validating the token, the program extracts the subject from the token, assumes it is the client ID, and then looks up the client from the database with the token sub. 

https://github.com/pocket-id/pocket-id/blob/ae269371da95cd55f94ad8862822a114fe9d166d/backend/internal/service/oidc_service.go#L1800

Of course, if the `sub` is not the client ID, then the lookup will fail, thus resulting in the final error message, "Invalid client assertion"

### Pocket ID Version

2.2.0

### Database

SQLite

### OS and Environment

Kubernetes. Deployment manifest with image `ghcr.io/pocket-id/pocket-id:v2.2.0`

### Log Output

```
Feb 23 18:06:42 ERR record not found app=pocket-id version=2.2.0 error="record not found" query="SELECT * FROM `oidc_clients` WHERE id = \"project_path:my-gitlab-group/my-repo:ref_type:branch:ref:my-branch-name\" ORDER BY `oidc_clients`.`id` LIMIT 1" duration=809.287µs rows=0 file=github.com/orandin/slog-gorm@v1.4.0/logger.go:163
Feb 23 18:06:42 WRN Request with errors: Error #01: invalid client assertion
app=pocket-id version=2.2.0 status=400 method=POST path=/api/oidc/token query="" route=/api/oidc/token ip=10.42.2.1 latency=1.857896ms referer="" user_agent=curl/8.17.0 body_size=36
```

For sake of interest, I'm trying exchange a [Gitlab pipeline token](https://docs.gitlab.com/ci/secrets/id_token_authentication/) with Pocket ID.

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes a regression that broke federated client credentials when the "sub" is not the same as the client ID.

See [this comment](https://github.com/pocket-id/pocket-id/issues/902#issuecomment-3961460340) with implementation notes and decisions around framing this in terms of identity federation, which is on purpose not compliant with RFC 7532 (however, it's possible to configure this to be fully RFC-7532 compliant)

- Fixes #1333
- Closes #902
- Closes #991

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
@copilot can you please update the E2E tests, which are currently failing, so they work with the updated code and rules? 🙏

File: backend/internal/dto/oidc_dto.go [hunk 1]
```diff
@@ -98,7 +98,8 @@ type OidcCreateTokensDto struct {
 }
 
 type OidcIntrospectDto struct {
-	Token string `form:"token" binding:"required"`
+	Token    string `form:"token" binding:"required"`
+	ClientID string `form:"client_id"`
```
Comment (kmendell) [inline backend/internal/dto/oidc_dto.go:102]: Should the client ID be required as well? This wouldnt work without a client id would it?

**Review by kmendell — APPROVED** [review]
Besides that one comment, It looks good to me :)

File: backend/internal/dto/oidc_dto.go (hunk 1 above)
Comment (ItalyPaleAle) [reply backend/internal/dto/oidc_dto.go:102]: Most people calling this endpoint would pass the client ID (and secret) as a Basic auth header. This is just an option for when using federation
