### PR TITLE
fix: add validation for callback URLs

### LINKED ISSUE #916: 🐛 Bug Report: URLs are not validated
### Reproduction steps

When creating a new client the Callback URLs and the Logout Callback URLs are not validated.

### Expected behavior

I expected the URLs would be validated that they contain a https:// scheme, a domain and a path.

### Actual Behavior

No URL input validation occurs.

### Pocket ID Version

1.10.0

### PR DESCRIPTION
**Pull request by stonith404**
Fixes #916

### CODE REVIEW

File: backend/internal/dto/validations.go [hunk 1]
```diff
@@ -60,3 +64,24 @@ func ValidateUsername(username string) bool {
 func ValidateClientID(clientID string) bool {
 	return validateClientIDRegex.MatchString(clientID)
 }
+
+// ValidateCallbackURL validates callback URLs with support for wildcards
+func ValidateCallbackURL(raw string) bool {
+	if raw == "" {
```
Comment (ItalyPaleAle) [inline backend/internal/dto/validations.go]: Do we need to allowlist `"*"` (allow all callbacks) too? I believe that's a valid one today

Comment (stonith404) [reply backend/internal/dto/validations.go]: You're right, thanks

**Review by kmendell — APPROVED** [review]
