### PR TITLE
fix: decouple images from app config service

### LINKED ISSUE #964: 🐛 Bug Report: Custom background image lost after update to v1.11.1
### Reproduction steps

After updating two instances to v1.11.1 (from v1.10.0) both no longer showed their custom background.  When I went to re-upload the custom background that operation failed with the following error recorded in the log:

`ERR Request with errors: Error #01: remove data/uploads/application-images/background.webp: no such file or directory`

In fact there was not (nor has there ever been for as far as back as I have backups?) a background.webp file in that folder.  Upon creating the file manually only then was I able to successfully re-upload my custom background.

### Expected behavior

To not lose a custom background as a result of an update (didn't see anything in the release notes about it, apologies if missed) and to not be blocked from uploading a custom background due to a file not existing.

### Actual Behavior

Lost custom background, could not re-upload without first manually creating placeholder/default (?) file.

### Pocket ID Version

v1.11.1

### Database

SQLite

### OS and Environment

Pocket ID v1.11.1 running in Docker v28.4.0 on Debian v12 running through Traefik v3.5.2.

### Log Output

`ERR Request with errors: Error #01: remove data/uploads/application-images/background.webp: no such file or directory`

### PR DESCRIPTION
**Pull request by stonith404**
This PR separates the handling of application images (such as the logo and background) from the `AppConfigService`. By decoupling this logic, the codebase becomes cleaner and avoids bugs caused by inconsistencies in file type management.

Currently, Pocket ID stores the file extension of uploaded images in the database at the time of upload. If a user later replaces images directly on the filesystem, the stored extension can fall out of sync with the actual file, preventing the image from being displayed. A similar issue occurred in #964, where users had uploaded a custom JPG image. Since the last release changed the default background image format in `AppConfigService` from JPG to WEBP, Pocket ID incorrectly assumed those users were using a WEBP file instead of their actual JPG, which led to display problems.

---
Closes #964

### CODE REVIEW

File: backend/internal/service/app_images_service.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+	if err != nil {
+		return "", "", err
+	}
+
+	mimeType := utils.GetImageMimeType(ext)
+	if mimeType == "" {
+		return "", "", fmt.Errorf("unsupported image type '%s'", ext)
+	}
+
+	imagePath := path.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", name, ext))
```
Comment (ItalyPaleAle) [inline backend/internal/service/app_images_service.go]: Use filepath, or this will have problems on Windows


```suggestion
	imagePath := filepath.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", name, ext))
```

File: backend/internal/service/app_images_service.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+
+	s.mu.Lock()
+	defer s.mu.Unlock()
+
+	currentExt, ok := s.extensions[imageName]
+	if !ok {
+		return fmt.Errorf("unknown application image '%s'", imageName)
+	}
+
+	imagePath := path.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", imageName, fileType))
```
Comment (ItalyPaleAle) [inline backend/internal/service/app_images_service.go]: ditto

```suggestion
	imagePath := filepath.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", imageName, fileType))
```

File: backend/internal/utils/file_util.go [hunk 3]
```diff
@@ -24,6 +25,15 @@ func GetFileExtension(filename string) string {
 	return filename
 }
 
+// SplitFileName splits a full file name into name and extension.
+func SplitFileName(fullName string) (name, ext string) {
+	dot := strings.LastIndexByte(fullName, '.')
```
Comment (ItalyPaleAle) [inline backend/internal/utils/file_util.go]: LastIndex is safer in case the file name contains non-ASCII characters

```suggestion
	dot := strings.LastIndex(fullName, ".")
```

File: backend/internal/utils/file_util.go [hunk 4]
```diff
@@ -24,6 +25,15 @@ func GetFileExtension(filename string) string {
 	return filename
 }
 
+// SplitFileName splits a full file name into name and extension.
+func SplitFileName(fullName string) (name, ext string) {
```
Comment (ItalyPaleAle) [inline backend/internal/utils/file_util.go:29]: Use [filepath.Ext](https://pkg.go.dev/path/filepath#example-Ext) ?

File: backend/internal/service/app_images_service.go [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+
+	if err := utils.SaveFile(file, imagePath); err != nil {
+		return err
+	}
+
+	if currentExt != "" && currentExt != fileType {
+		oldImagePath := path.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", imageName, currentExt))
```
Comment (ItalyPaleAle) [inline backend/internal/service/app_images_service.go]:
```suggestion
		oldImagePath := filepath.Join(common.EnvConfig.UploadPath, "application-images", fmt.Sprintf("%s.%s", imageName, currentExt))
```

**Review by ItalyPaleAle — COMMENTED** [review]
A few of small comments but overall LGTM

For the future, thoughts on storing uploaded images directly in the database? They would then be loaded once the app starts up. It would solve all kinds of issues with keeping the filesystem in sync

File: backend/internal/utils/file_util.go (hunk 4 above)
Comment (ItalyPaleAle) [reply backend/internal/utils/file_util.go:29]: I guess if we need both the name and extension, easier to do it this way

**Comment by stonith404** [comment]
@ItalyPaleAle thanks for the review, Personally I’m not a big fan of storing files in the database especially with SQLite, since it increases the DB size. I prefer keeping data and files separate.

With the changes in this PR, the filesystem is now the single source of truth, and no image related data is stored in the database anymore. This should resolve all the sync issues we had before.

What would make sense though, would be to to implement S3 support in the future, because this seems highly requested and with this feature Pocket ID should be ready to run in a serverless environment.
